---
config:
  layout: elk
---
flowchart LR
 subgraph System["Banking Fraud Detection & Analytics"]
        UC1("Manage accounts")
        UC2("Manage transactions")
        UC3("Manage employee roles")
        UC4("Approve / Reject loans")
        UC5("View customer history")
        UC6("Deposit / Withdraw / Transfer")
        UC7("Apply for loan")
        UC8("Fraud detection & alerts")
  end
    Admin(["Admin"]) --> UC1 & UC2 & UC3
    Emp(["Bank Employee"]) --> UC4 & UC5
    Cust(["Customer"]) --> UC6 & UC7
    UC2 --> UC8
